# WRITE FIT IN, WHEN YOU ARE BORN TO STAND OUT!
#WRITE A PROGRAM TO FIND THE LENGTH OF THE STRING
a="why FIT IN, WHEN YOU ARE BORN TO STAND OUT!"

# print(len(a))

##WRITE A PROGRAM TO CHECK HOW MANY TIME ALPHABET 'o' is occuring
# print(a.count('O'))

### WRITE A PROGRAM TO CONVERT THE WHOLE STRING INTO LOWER # AND UPPER CASE
# print(a.lower())
# print(a.upper())

#### WRITE APROGRAM TO CONVERT THE FOLLOWING STRING INTO A TITTLE CASE
# print(a.title())

##### WRITE A PROGRAM TO  FIND THE INDEX NUMMBER OF "fit in"
print(a.find("FIT IN"))
