# FIBONACI SERIES 
# a  = 0
# b = 1
# print(a)
# print(b)
# for i in range(2, 11):
#     c = a + b
#     print(c)
#     a = b
#     b = c

 
 ## CHECK PRIM NUMBERY
# n = int(input("Enter a number: "))
# if n<=1:
#     print("Not a prime number")
# else:
#     for i in range(2, n):
#         if n%2 == 0:
#             print("Not ff a prime number")
#             break
#         else:
#           print("Prime number")


### CHECK PALINDROME
# a =int(input("Enter a number: "))
# temp = a
# rev = 0
# while a>0:
#     dig = a%10
#     rev = rev*10 + dig
#     a //= 10
# if temp == rev:
#     print("Palindrome")
# else:
#     print("Not a palindrome")


#### Area  Calculate 
