# a = "OOTD.YOLO.ASAP.BRB.GTG.OTW"
# b = a.split(".")
# print(b)

# SORTED VALUE OF A in accesind order
# a = input(" enter a name: ")
# b = sorted(a)
# print(b)



### Write a program to remove a given character from a string
# a = "hello"
# b = a.replace("e", "")
# print(b)



# Z = "F.R.I.E.N.D.S"
# 4. Write a program to remove dot(.) from the following string
# a = "F.R.I.E.N.D.S"
# b = a.replace(".","")
# print(b)


#WRITE A PROGRAM TO CHECK THE NUMBER OF ACCURENCE OF A 
#SUBSTRING IN A STRING
# a = "She sells seashells on the sea shore"
# b = a.count("sea")
# print(b)

